// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLKzbjmbLTWI2v7iGe2B_d1YGfU0uUgRY',
    appId: '1:470490185691:web:f69af5dad0776a188eb1fe',
    messagingSenderId: '470490185691',
    projectId: 'student-registration-c840e',
    authDomain: 'student-registration-c840e.firebaseapp.com',
    databaseURL: 'https://student-registration-c840e-default-rtdb.firebaseio.com',
    storageBucket: 'student-registration-c840e.appspot.com',
    measurementId: 'G-NBY0J1Q1SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdMblsHQJKImncO5f3sf_QqaNYaaPV77w',
    appId: '1:470490185691:android:7706606cad630e028eb1fe',
    messagingSenderId: '470490185691',
    projectId: 'student-registration-c840e',
    databaseURL: 'https://student-registration-c840e-default-rtdb.firebaseio.com',
    storageBucket: 'student-registration-c840e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-qBKQLPPD84acbfqpmVgyi3-MkOk-2PM',
    appId: '1:470490185691:ios:eb0db9fa28e138dc8eb1fe',
    messagingSenderId: '470490185691',
    projectId: 'student-registration-c840e',
    databaseURL: 'https://student-registration-c840e-default-rtdb.firebaseio.com',
    storageBucket: 'student-registration-c840e.appspot.com',
    iosBundleId: 'com.example.studentRegistration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-qBKQLPPD84acbfqpmVgyi3-MkOk-2PM',
    appId: '1:470490185691:ios:eb0db9fa28e138dc8eb1fe',
    messagingSenderId: '470490185691',
    projectId: 'student-registration-c840e',
    databaseURL: 'https://student-registration-c840e-default-rtdb.firebaseio.com',
    storageBucket: 'student-registration-c840e.appspot.com',
    iosBundleId: 'com.example.studentRegistration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLKzbjmbLTWI2v7iGe2B_d1YGfU0uUgRY',
    appId: '1:470490185691:web:70f53e22d5e615a48eb1fe',
    messagingSenderId: '470490185691',
    projectId: 'student-registration-c840e',
    authDomain: 'student-registration-c840e.firebaseapp.com',
    databaseURL: 'https://student-registration-c840e-default-rtdb.firebaseio.com',
    storageBucket: 'student-registration-c840e.appspot.com',
    measurementId: 'G-HW83DRHMB1',
  );
}
